#!/usr/bin/env bash
#
# Writes backend/.env and ui/.env.local from the deployed stacks.
#
# Every identifier is read from CloudFormation rather than typed. Generating the files
# from the deployed stacks avoids hand-copying identifiers: a wrong knowledge base ID
# returns no results, and a wrong Cognito client ID rejects every token.
#
# Both files are gitignored. This refuses to overwrite an existing one.
set -euo pipefail

STAGE="${1:-dev}"
REGION="${2:-us-east-1}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

output() { # stack, key
  aws cloudformation describe-stacks --stack-name "$1" --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$2'].OutputValue" --output text 2>/dev/null \
    | grep -v '^None$' || true
}

refuse_if_present() {
  if [ -f "$1" ]; then
    echo "Refusing to overwrite $1 — delete it first if you want it regenerated." >&2
    exit 1
  fi
}

KB_ID=$(output "UnifiedSearch-${STAGE}-KnowledgeBase" KnowledgeBaseId)
DS_ID=$(output "UnifiedSearch-${STAGE}-KnowledgeBase" DataSourceId)
MEMORY_ID=$(output "UnifiedSearch-${STAGE}-Memory" MemoryId)
POOL_ID=$(output "UnifiedSearch-${STAGE}-Identity" UserPoolId)
CLIENT_ID=$(output "UnifiedSearch-${STAGE}-Identity" UserPoolClientId)
HOSTED_UI=$(output "UnifiedSearch-${STAGE}-Identity" HostedUiDomain)

if [ -z "$KB_ID" ]; then
  echo "No knowledge base found for stage '${STAGE}'. Deploy it first: make sample" >&2
  exit 1
fi

if [ -z "$POOL_ID" ]; then
  echo "No identity stack found for stage '${STAGE}'." >&2
  echo "The backend cannot start without a user pool. Deploy one with:" >&2
  echo "  make sample-deploy IDENTITY=true" >&2
  echo "or set COGNITO_USER_POOL_ID and COGNITO_CLIENT_ID by hand for your own pool." >&2
  exit 1
fi

BACKEND_ENV="$ROOT/backend/.env"
UI_ENV="$ROOT/ui/.env.local"
refuse_if_present "$BACKEND_ENV"
refuse_if_present "$UI_ENV"

{
  echo "# Generated by make sample-env from the deployed stacks. Not committed."
  echo "COGNITO_USER_POOL_ID=${POOL_ID}"
  echo "COGNITO_CLIENT_ID=${CLIENT_ID}"
  echo "CORS_ALLOWED_ORIGINS=http://localhost:5173"
  echo "AWS_REGION=${REGION}"
  echo "PORT=3001"
  echo "KNOWLEDGE_BASE_ID=${KB_ID}"
  echo "DATA_SOURCE_ID=${DS_ID}"
  if [ -n "$MEMORY_ID" ]; then
    echo "MEMORY_ID=${MEMORY_ID}"
  else
    echo "# MEMORY_ID unset: chat is single-turn, and the API reports that through"
    echo "# GET /knowledgebase/capabilities so the UI says so rather than appearing to forget."
  fi
} > "$BACKEND_ENV"

{
  echo "# Generated by make sample-env from the deployed stacks. Not committed."
  echo "VITE_API_BASE_URL=http://localhost:3001"
  echo "VITE_COGNITO_DOMAIN=${HOSTED_UI}"
  echo "VITE_COGNITO_CLIENT_ID=${CLIENT_ID}"
} > "$UI_ENV"

echo "Wrote:"
echo "  backend/.env"
echo "  ui/.env.local"
echo
echo "Start both halves:"
echo "  make api    # terminal 1"
echo "  make web    # terminal 2"
echo
echo "Then sign in at http://localhost:5173 with an account from 'make sample-users'."
